name             'drupal'
maintainer       'Kenneth Copeland Ministries'
maintainer_email 'rferguson@kcm.org'
license          'All rights reserved'
description      'Installs/Configures Drupal 8'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'apt'
depends          'apache2'
depends          'php'